[EMB-13237] Allow to initialize report class without monitor installation
embrace-io/KSCrash pull request #13
Opened 2023-07-03 20:24 UTC by jdbandoni

2023-07-03 20:28 UTC, ArielDemarco approved these changes
I'd just add some docs/comments so we don't forget what's the idea behind those changes

2023-07-10 20:01 UTC, blakdragan7 requested changes

2023-07-10 20:01 UTC, blakdragan7 commented on Source/KSCrash/Recording/KSCrashC.c
> +    kscrs_initialize(appName, path);
This changes internal global variables. Callling this more the once (i.e. for loading extension crashes from host app) will cause a problem.

2023-07-10 20:01 UTC, blakdragan7 commented on Source/KSCrash/Recording/KSCrash.m
> ++ (instancetype) sharedInstanceWithBasePath:(NSString *)basePath andBundleName:(NSString *)bundleName
If the goal of this change is to allow loading crashes from the extension app in the host app then this approach will not work. I recommend exposing a "static" function in KSCrash instance that directly access the internal "loading" of the crash report functions instead.

2023-07-10 20:01 UTC, blakdragan7 commented
I do not think this is going to accomplish what you want it to. We can talk directly if you want to make a better way to do this.

2023-07-18 17:06 UTC, blakdragan7 commented
I just don't understand what the point of doing this is. Why do we need to set the bundle on the class instance ?

2023-07-18 18:15 UTC, blakdragan7 approved these changes

2023-07-18 18:18 UTC, merged